resource_rules:
    issues:
        rules:
            - name: Stale Issues policy
              conditions:
                  date:
                      attribute: updated_at
                      condition: older_than
                      interval_type: days
                      interval: 7
                  state: opened
                  labels:
                      - needs-investigation
                      - stale-warning
                  forbidden_labels:
                      - stale
                      - status::'{to-do, in-dev, qa, done}'
              limits:
                  most_recent: 50
              actions:
                  labels:
                      - stale
                  comment: |
                      {{author}} This issue has been had no activity for 30 days. It has been marked as stale.
            - name: Stale warning
              conditions:
                  date:
                      attribute: updated_at
                      condition: older_than
                      interval_type: days
                      interval: 23
                  state: opened
                  labels:
                      - needs-investigation
                  forbidden_labels:
                      - status::'{to-do, in-dev, qa, done}'
              limits:
                  most_recent: 50
              actions:
                  labels:
                      - stale-warning
                  mention:
                      - MasterSaberD1996
                  comment: |
                      {{author}} This issue has had no activity for 23 days. If there is no activity, in 7 this issue will be marked as stale
                  remove_labels:
                      - stale-warning
