name: "Bug Report"
description: "This form is to report unexpected behavior in the plugin"
labels:
- bug
body:
- type: markdown
  attributes:
    value: |
      Thank you for your patience with these plugins and for your time submitting a bug report.

      Help me help you! Please fill out the entire form below with as much detail as possible to help me reproduce the bug.
- type: dropdown
  id: plugin-name
  attributes:
    label: "Test issue"
    description: "This is just a test"
    options:
    - "Firebase Cypress"
    - "NX Firebase"
