name: "Bug Report"
description: "This form is to report unexpected behavior in the plugin"
labels:
- bug
body:
- type: textarea
  attributes:
    label: "Test issue"
    description: "This is just a test"
