name: "Feature request"
description: "This form is to request a new feature or plugin"
labels:
- enhancement
body:
- type: textarea
  attributes:
    label: "What is the problem you are trying to solve?"
    description: "Please provide a clear and concise description of what you are trying to accomplish"
  validations:
    required: true
- type: textarea
  id: solution
  attributes:
    label: "Proposed solution"
    description: "Please provide what you would like to have happen. The more detail provided, the better."
  validations:
    required: true
- type: textarea
  id: context
  attributes:
    label: "Additional context"
    description: "Add any other context that you can to help provide a scope to your request"
